### ISSUE TITLE
[Drone] セパレータを超えたエイリアスはできない

### ISSUE THREAD

**Issue by srz-zumix** [srz-zumix/ci-yaml#2]
```
kind: pipeline
name: main

clone: &clone-default
  depth: 1

steps:
  - name: test
    image: gcc
    commands:
      - echo test
    when: &condition
      branch:
        - master

---
kind: pipeline
name: copy

steps:
   - name: hello
     image: gcc
     when: *condition # yaml: unknown anchor 'condition' referenced
     commands:
       - echo hello
```
